# .github/workflows/ci.yml
name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, mysql, zip
          coverage: none

      - name: Vérifier PHP
        run: php -v

      - name: Installer les dépendances Composer
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copier le fichier .env
        run: cp .env.example .env

      - name: Générer la clé d'application Laravel
        run: php artisan key:generate

      - name: Lancer les tests
        run: php artisan test
